version: "3.9"

volumes:
  localstack_data:

networks:
  frame-extractor:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8180:8080"
    volumes:
      - .:/app:cached
    depends_on:
      - localstack
    networks:
      - frame-extractor
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566  # URL do DynamoDB no LocalStack

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,s3  # Ativando DynamoDB e S3
      - DEBUG=${DEBUG-}
      - LOCALSTACK_PERSISTENCE=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "localstack_data:/var/lib/localstack"
    networks:
      - frame-extractor


