volumes:
  db_servicos_data:
networks:
  frame-extractor:
    external: false

services:
  db-frame-extractor:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_servicos_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - frame-extractor

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
    volumes:
      - .:/app
    depends_on:
      - db-frame-extractor
    networks:
      - frame-extractor