apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-deployment
  namespace: frame-extractor
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: "dynamodb,s3,ses"
        - name: DEBUG
          value: ""
        - name: LOCALSTACK_PERSISTENCE
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        volumeMounts:
        - name: localstack-data
          mountPath: /var/lib/localstack
      volumes:
      - name: localstack-data
        persistentVolumeClaim:
          claimName: localstack-pvc
